### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by BLPARMAR** [lcbb/pyDAEDALUS#6]
As I go for the pytho DAEDserve.py step, this is the error I'm facing

**(DAEDALUS) C:\BHAGYESH PARMAR\TD COMPUTATIONAL\pyDAEDALUSX-win32-x64\pyDAEDALUS-master>python 

pyDAEDALUS/DAEDserve.py

Traceback (most recent call last):
  File "pyDAEDALUS/DAEDserve.py", line 8, in <module>
    from Automated_Design.DX_cage_design import DX_cage_design
  File "C:\BHAGYESH PARMAR\TD COMPUTATIONAL\pyDAEDALUSX-win32-x64\pyDAEDALUS-master\pyDAEDALUS\Automated_Design\DX_cage_design.py", line 6, in <module>
    from Automated_Design.adj_scaf_nick_pos import adj_scaf_nick_pos, \
  File "C:\BHAGYESH PARMAR\TD COMPUTATIONAL\pyDAEDALUSX-win32-x64\pyDAEDALUS-master\pyDAEDALUS\Automated_Design\adj_scaf_nick_pos.py", line 3, in <module>
    from Automated_Design.util import intersect_lists
  File "C:\BHAGYESH PARMAR\TD COMPUTATIONAL\pyDAEDALUSX-win32-x64\pyDAEDALUS-master\pyDAEDALUS\Automated_Design\util.py", line 1, in <module>
    import networkx as nx
  File "C:\Users\parma\.conda\envs\DAEDALUS\lib\site-packages\networkx\__init__.py", line 98, in <module>
    import networkx.utils
  File "C:\Users\parma\.conda\envs\DAEDALUS\lib\site-packages\networkx\utils\__init__.py", line 2, in <module>
    from networkx.utils.decorators import *
  File "C:\Users\parma\.conda\envs\DAEDALUS\lib\site-packages\networkx\utils\decorators.py", line 14, in <module>
    from decorator import decorator
  File "C:\Users\parma\.conda\envs\DAEDALUS\lib\site-packages\decorator.py", line 162
    print('Error in generated code:', file=sys.stderr)
                                          ^
### SyntaxError: invalid syntax**

**Comment by Sin-0202** [comment]
I had the same problem when I ran the code, did you solve it now?

**Comment by BLPARMAR** [comment]
I couldn't and also i didn't find anything on the web. Let me know if you
find something.
